-- Database schema for ProductIQ

-- Table for storing static product legal database (populated with common import categories)
CREATE TABLE IF NOT EXISTS product_legal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL UNIQUE,
    keywords TEXT[] NOT NULL,
    bis_required BOOLEAN DEFAULT FALSE,
    bis_standard TEXT,
    hsn_code TEXT,
    customs_duty_pct NUMERIC DEFAULT 0,
    gst_pct NUMERIC DEFAULT 18,
    fssai_required BOOLEAN DEFAULT FALSE,
    dgft_status TEXT DEFAULT 'Freely importable',
    legal_metrology BOOLEAN DEFAULT TRUE,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Table for storing generated market intelligence reports (cached/saved reports)
CREATE TABLE IF NOT EXISTS product_reports (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_name TEXT NOT NULL UNIQUE,
    report_json JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Index for fast lookups on product names
CREATE INDEX IF NOT EXISTS idx_product_reports_name ON product_reports (product_name);
