/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#0b522d",
        "on-secondary-fixed-variant": "#404945",
        "tertiary-fixed-dim": "#ffb2ba",
        "background": "#f8f9ff",
        "on-primary-fixed": "#00210e",
        "on-secondary-fixed": "#151d1b",
        "on-tertiary-container": "#ffaeb6",
        "surface-bright": "#f8f9ff",
        "outline": "#707971",
        "secondary-fixed-dim": "#bfc9c4",
        "surface-variant": "#d9e3f4",
        "surface-container-highest": "#d9e3f4",
        "tertiary": "#64252f",
        "primary-fixed": "#aef2c0",
        "surface-dim": "#d1dbec",
        "error-container": "#ffdad6",
        "surface-tint": "#2a6a43",
        "primary": "#004322",
        "primary-fixed-dim": "#93d5a5",
        "on-error": "#ffffff",
        "on-surface": "#121c28",
        "outline-variant": "#c0c9bf",
        "on-primary-container": "#90d2a2",
        "tertiary-container": "#803b45",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#eaf1ff",
        "on-tertiary": "#ffffff",
        "secondary": "#57605d",
        "secondary-fixed": "#dce5e0",
        "surface-container-high": "#dfe9fa",
        "on-secondary-container": "#5c6561",
        "surface-container": "#e5eeff",
        "tertiary-fixed": "#ffd9dc",
        "primary-container": "#1a5c36",
        "on-tertiary-fixed-variant": "#74313b",
        "surface-container-low": "#eef4ff",
        "inverse-primary": "#93d5a5",
        "secondary-container": "#d9e2dd",
        "surface": "#f8f9ff",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "on-background": "#121c28",
        "on-surface-variant": "#404941",
        "inverse-surface": "#27313e",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#3c0612"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "0.5rem",
        "lg": "2rem",
        "margin": "32px",
        "gutter": "24px",
        "md": "1.5rem",
        "sm": "1rem",
        "xl": "3rem",
        "base": "4px"
      },
      fontFamily: {
        "headline-lg": ["Syne", "sans-serif"],
        "headline-md": ["Syne", "sans-serif"],
        "body-lg": ["Instrument Sans", "sans-serif"],
        "display-lg": ["Syne", "sans-serif"],
        "body-md": ["Instrument Sans", "sans-serif"],
        "data-value": ["DM Mono", "monospace"],
        "data-label": ["DM Mono", "monospace"],
        "caption": ["Instrument Sans", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "data-value": ["13px", { "lineHeight": "1.2", "fontWeight": "400" }],
        "data-label": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "caption": ["12px", { "lineHeight": "1.4", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
